default: # This is the profile name dbt is looking for
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}" # Ensure port is an integer
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public # You can change this to your desired schema
      threads: 1
      connect_timeout: 10